apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-{{ .Values.color }}
  labels:
    app: {{ .Values.appName }}
    version: {{ .Values.color }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      version: {{ .Values.color }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        version: {{ .Values.color }}
    spec:
      containers:
      - name: nodejs-app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000