apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-{{ .Values.color }}
  labels:
    app: {{ .Values.appName }}
    version: {{ .Values.color }}
spec:
  selector:
    app: {{ .Values.appName }}
    version: {{ .Values.color }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP